import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Earbuds Pro",
    description: "Premium wireless earbuds with active noise cancellation and 30-hour battery life.",
    price: 149.99,
    discount: 20,
    image: "/modern-wireless-earbuds-black.jpg",
    additionalImages: ["/wireless-earbuds-charging-case.jpg", "/wireless-earbuds-close-up.jpg"],
    category: "electronics",
    rating: 4.8,
    reviews: 1249,
  },
  {
    id: "2",
    name: "Smart Watch Ultra",
    description: "Advanced fitness tracking, heart rate monitoring, and GPS navigation in a sleek design.",
    price: 399.99,
    discount: 15,
    image: "/black-smartwatch-modern-design.jpg",
    additionalImages: ["/smartwatch-display-screen.jpg", "/smartwatch-on-wrist.png"],
    category: "electronics",
    rating: 4.9,
    reviews: 2156,
  },
  {
    id: "3",
    name: "Designer Leather Jacket",
    description: "Premium genuine leather jacket with modern cut and exceptional comfort.",
    price: 299.99,
    image: "/black-leather-jacket-fashion.jpg",
    additionalImages: ["/leather-jacket-detail-zipper.jpg", "/leather-jacket-back.png"],
    category: "fashion",
    rating: 4.7,
    reviews: 892,
  },
  {
    id: "4",
    name: "Running Shoes Elite",
    description: "High-performance running shoes with advanced cushioning technology.",
    price: 179.99,
    discount: 25,
    image: "/white-blue-running-shoes-modern.jpg",
    additionalImages: ["/running-shoes-side-view.png", "/running-shoes-sole-detail.jpg"],
    category: "sports",
    rating: 4.6,
    reviews: 1543,
  },
  {
    id: "5",
    name: "Minimalist Coffee Table",
    description: "Elegant Scandinavian-style coffee table crafted from sustainable oak wood.",
    price: 449.99,
    image: "/wooden-coffee-table-modern-minimalist.jpg",
    additionalImages: ["/coffee-table-in-living-room.jpg", "/coffee-table-wood-texture.jpg"],
    category: "home",
    rating: 4.8,
    reviews: 678,
  },
  {
    id: "6",
    name: "4K Ultra HD Camera",
    description: "Professional mirrorless camera with 45MP sensor and 8K video recording.",
    price: 2499.99,
    discount: 10,
    image: "/professional-camera-mirrorless-black.jpg",
    additionalImages: ["/camera-lcd-screen-display.jpg", "/camera-with-lens-attached.jpg"],
    category: "electronics",
    rating: 4.9,
    reviews: 543,
  },
  {
    id: "7",
    name: "Yoga Mat Premium",
    description: "Extra thick eco-friendly yoga mat with superior grip and cushioning.",
    price: 59.99,
    image: "/purple-yoga-mat-rolled.jpg",
    additionalImages: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "sports",
    rating: 4.7,
    reviews: 2341,
  },
  {
    id: "8",
    name: "Ceramic Plant Pot Set",
    description: "Handcrafted ceramic planters in various sizes with drainage holes.",
    price: 79.99,
    discount: 30,
    image: "/placeholder.svg?height=400&width=400",
    additionalImages: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "home",
    rating: 4.5,
    reviews: 987,
  },
  {
    id: "9",
    name: "Denim Jeans Classic",
    description: "Timeless slim-fit denim jeans with stretch fabric for all-day comfort.",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=400",
    additionalImages: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "fashion",
    rating: 4.6,
    reviews: 1876,
  },
  {
    id: "10",
    name: "Portable Bluetooth Speaker",
    description: "360-degree sound with waterproof design and 20-hour battery life.",
    price: 129.99,
    discount: 20,
    image: "/placeholder.svg?height=400&width=400",
    additionalImages: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "electronics",
    rating: 4.7,
    reviews: 1432,
  },
  {
    id: "11",
    name: "Cashmere Sweater",
    description: "Luxuriously soft 100% cashmere sweater in versatile neutral tones.",
    price: 249.99,
    image: "/placeholder.svg?height=400&width=400",
    additionalImages: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "fashion",
    rating: 4.9,
    reviews: 654,
  },
  {
    id: "12",
    name: "Weighted Blanket",
    description: "Therapeutic weighted blanket for better sleep and relaxation.",
    price: 119.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    additionalImages: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "home",
    rating: 4.8,
    reviews: 2109,
  },
]
